spring:
#  h2:
#    console:
#      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
#      path: /test_db  # 콘솔의 경로
#  datasource:
#    driver-class-name: org.h2.Driver  #h2 드라이버 설정 (개발환경)
#    url: jdbc:h2:tcp://localhost/~/test  #접속 URL
#    username: sa  # 사용자 이름 (로그인 시 사용)
#    password:     # 사용자 암호 (로그인 시 사용)
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://uahage2.c7qbk7qns6ot.ap-northeast-2.rds.amazonaws.com:5432/uahage_dev_v2
    username: postgres
    password: hohocom!
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0